
#!/bin/bash
#Menu
clear
echo -e " "
echo -e "\033[01;32m  }~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{"
echo -e "  {    Welcome to Server Debian7-8    }"
echo -e "  }~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{"
echo -e "  {         Script mod by Tao	       }"
echo -e "  }~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{"
echo -e "  {   Enter { menu } Show menu items  }"
echo -e "  }~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{"
echo -e " "
echo -e "\033[1;31m { a } adduser Create SSH & OpenVPN"
echo -e "\033[1;33m { b } test new  user"
echo -e "\033[1;34m { c } Change Name"
echo -e "\033[1;35m { d } Change Password,Change de logins,Change Exp"
echo -e "\033[1;36m { e } delete user SSH & OpenVPN"
echo -e "\033[1;32m { f } Auto delete user Expres"
echo -e "\033[1;33m { g } user view all member SSH & OpenVPN"
echo -e "\033[1;34m { h } restart service, OpenVPN and SSH"
echo -e "\033[1;35m { i } speedtest VPS"
echo -e "\033[1;36m { j } Check bandwidth total data internet"
echo -e "\033[1;31m { k } view user online"
echo -e "\033[1;33m { l } about this system"
echo -e "\033[1;34m { m } ban user"
echo -e "\033[1;35m { n } unban user"
echo -e "\033[1;31m { o } Install And Update File HTTP"
echo -e "\033[1;32m { p } Add And Edit Credit App HTTP"
echo -e "\033[1;33m { q } about script auto install"
echo -e "\033[1;34m { r } Setting Reboot Time"
echo -e "\033[1;34m { s } Backup And Restore User"
echo -e "\033[1;35m { reboot } reboot VPS"
echo -e "\033[1;36m { exit } close Putty/Connecbot/JuiceSSH"
echo -e "\033[1;32m"
